language: node_js
sudo: false
install: true
git:
  depth: 5
os:
 - linux
env:
  - TEST=true
node_js:
  - "7.4"
  - "6.9"
  - "5.12"
  - "4.6"
  - "iojs-v3.3"
  - "iojs-v2.5"
  - "iojs-v1.8"
  - "0.12"
  - "0.10"
  - "0.8"
